const state={tab:"agenda",data:{},pending:null,collapsed:false};const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const api=async(name,...args)=>{const r=await window.pywebview.api[name](...args);if(!r.ok)throw new Error(r.error);return r.data};
document.getElementById("date").textContent=new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).format(new Date());
window.addEventListener("pywebviewready",load);document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;document.querySelectorAll("nav button").forEach(x=>x.classList.toggle("active",x===b));render()});
document.getElementById("command").onkeydown=e=>{if(e.key==="Enter")parseCommand()};
document.getElementById("collapse").onclick=()=>{state.collapsed=!state.collapsed;document.getElementById("main").classList.toggle("collapsed",state.collapsed);document.getElementById("collapse").textContent=state.collapsed?"‹":"›"};
document.getElementById("connect").onclick=connectToggle;
async function load(){try{state.data=await api("bootstrap");document.getElementById("syncText").textContent=state.data.connected?`Google • ${state.data.sync.status}`:"Modo local • desconectado";document.getElementById("connect").style.color=state.data.connected?"var(--green)":"";const pending=(state.data.suggestions||[]).filter(x=>x.status==="pendente").length;document.getElementById("badge").textContent=pending||"";render()}catch(e){error(e)}}
function render(){document.getElementById("content").innerHTML=({agenda,goals,suggestions})[state.tab]()}
function agenda(){const groups={};(state.data.events||[]).forEach(e=>{const d=e.start.slice(0,10);(groups[d]??=[]).push(e)});return `<div class="toolbar"><h2>PRÓXIMOS 7 DIAS</h2><button class="secondary" onclick="openEventForm()">+ Manual</button></div><div class="connection"><span class="dot" style="background:${state.data.connected?"var(--green)":"var(--muted)"}"></span>${state.data.connected?"Sincronizado com o Google Agenda":"Conecte o Google para consultar e criar eventos reais"}</div>${Object.keys(groups).length?Object.entries(groups).map(([date,events])=>`<div class="day"><div class="day-head"><strong>${formatDay(date)}</strong></div>${events.map(eventHtml).join("")}</div>`).join(""):`<div class="empty">Nenhum evento sincronizado.<br>${state.data.connected?"Sua semana está livre.":"Conecte o Google Agenda ou trabalhe com metas locais."}</div>`}`}
function eventHtml(e){return `<div class="event"><time>${time(e.start)}</time><div><strong>${esc(e.title)}</strong><small>${esc(e.location||"Sem local")} • até ${time(e.end)}</small></div><button onclick='openEventMenu(${JSON.stringify(JSON.stringify(e))})'>•••</button></div>`}
function goals(){const rows=state.data.goals||[];return `<div class="toolbar"><h2>METAS LOCAIS</h2><button class="primary" onclick="openGoal()">+ Meta</button></div>${["diaria","semanal"].map(p=>`<div class="period">${p.toUpperCase()}</div>${rows.filter(g=>g.period===p).map(g=>`<div class="goal ${g.done?"done":""}"><input type="checkbox" ${g.done?"checked":""} onchange="toggleGoal(${g.id})"><label>${esc(g.label)}</label></div>`).join("")||'<div class="empty">Nenhuma meta.</div>'}`).join("")}`}
function suggestions(){const rows=state.data.suggestions||[];return `<div class="toolbar"><h2>SUGESTÕES</h2><button class="primary" onclick="openSuggestion()">+ Sugestão</button></div>${rows.map(s=>`<div class="suggestion"><strong>${esc(s.title)}</strong><small>${formatDateTime(s.starts_at)} • ${esc(s.status)}</small>${s.status==="pendente"?`<div class="actions"><button class="secondary" onclick="respond(${s.id},false)">Recusar</button><button class="primary" onclick="respond(${s.id},true)">Revisar e aceitar</button></div>`:""}</div>`).join("")||'<div class="empty">Nenhuma sugestão pendente.</div>'}`}
async function parseCommand(){const text=document.getElementById("command").value.trim();if(!text)return;try{review("create",await api("parse_event",text));document.getElementById("command").value=""}catch(e){error(e)}}
function openEventForm(data={}){form("NOVO EVENTO","Compromisso manual",eventFields(data),()=>{const d=formData();review(data.id?"update":"create",{...data,...d})})}
function eventFields(d){return field("title","Título","text",d.title)+field("start","Início","datetime-local",localValue(d.start))+field("end","Término","datetime-local",localValue(d.end))+field("location","Local","text",d.location)+field("description","Descrição","textarea",d.description)}
function openGoal(){form("NOVA META","Defina um objetivo",field("label","Meta","text")+`<div class="field"><label>Período</label><select name="period"><option value="diaria">Diária</option><option value="semanal">Semanal</option></select></div>`,async()=>{try{await api("save_goal",formData());document.getElementById("formDialog").close();await load()}catch(e){error(e)}})}
function openSuggestion(){form("NOVA SUGESTÃO","Proponha um horário",eventFields({}),async()=>{try{await api("save_suggestion",formData());document.getElementById("formDialog").close();await load()}catch(e){error(e)}})}
function form(kicker,title,body,next){document.getElementById("formKicker").textContent=kicker;document.getElementById("formTitle").textContent=title;document.getElementById("formBody").innerHTML=body;document.getElementById("formNext").onclick=next;document.getElementById("formDialog").showModal()}
function field(name,label,type,value=""){return `<div class="field"><label>${label}</label>${type==="textarea"?`<textarea name="${name}">${esc(value)}</textarea>`:`<input name="${name}" type="${type}" value="${esc(value||"")}">`}</div>`}
function formData(){return Object.fromEntries(new FormData(document.querySelector("#formDialog form")).entries())}
function openEventMenu(raw){const e=JSON.parse(raw);form("EVENTO SINCRONIZADO",e.title,`<div class="review"><strong>${esc(e.title)}</strong><span>${formatDateTime(e.start)}–${time(e.end)}</span></div>`,()=>{document.getElementById("formDialog").close();openEventForm(e)});const body=document.getElementById("formBody");body.innerHTML+=`<button type="button" class="danger" style="margin-top:12px" onclick='review("delete",${JSON.stringify(JSON.stringify(e))})'>Excluir evento</button>`}
function review(action,data){if(typeof data==="string")data=JSON.parse(data);state.pending={action,data};document.getElementById("previewTitle").textContent=action==="delete"?"Excluir compromisso?":"Revise o compromisso";document.getElementById("previewBody").innerHTML=`<div class="review"><strong>${esc(data.title)}</strong><span>${formatDateTime(data.start)} até ${time(data.end)}</span><span>${esc(data.location||"Sem local")}</span></div>`;document.getElementById("confirmAction").className=action==="delete"?"danger":"primary";document.getElementById("confirmAction").textContent=action==="delete"?"Confirmar exclusão":"Confirmar no Google";document.getElementById("confirmAction").onclick=commit;document.getElementById("formDialog").close();document.getElementById("preview").showModal()}
async function commit(){try{if(!state.data.connected)throw new Error("Conecte o Google Agenda antes de confirmar.");await api("commit_event",state.pending.action,state.pending.data);document.getElementById("preview").close();toast("Google Agenda atualizado com segurança.");await load()}catch(e){error(e)}}
async function toggleGoal(id){try{await api("toggle_goal",id);await load()}catch(e){error(e)}}
async function respond(id,accepted){try{if(accepted){const s=state.data.suggestions.find(x=>x.id===id);state.pending={suggestionId:id,action:"suggestion",data:{title:s.title,start:s.starts_at,end:s.ends_at,location:s.location}};document.getElementById("previewBody").innerHTML=`<div class="review"><strong>${esc(s.title)}</strong><span>${formatDateTime(s.starts_at)}</span></div>`;document.getElementById("confirmAction").onclick=async()=>{try{await api("respond_suggestion",id,true);document.getElementById("preview").close();await load()}catch(e){error(e)}};document.getElementById("preview").showModal()}else{await api("respond_suggestion",id,false);await load()}}catch(e){error(e)}}
async function connectToggle(){try{if(state.data.connected){state.pending={};document.getElementById("previewTitle").textContent="Desconectar Google Agenda?";document.getElementById("previewBody").textContent="O token será removido do Gerenciador de Credenciais do Windows. Seus eventos não serão apagados.";document.getElementById("confirmAction").onclick=async()=>{await api("disconnect_google");document.getElementById("preview").close();await load()};document.getElementById("preview").showModal()}else{const path=await api("choose_google_credentials");if(path){await api("connect_google",path);await load()}}}catch(e){error(e)}}
async function backup(){try{toast(`Backup: ${await api("backup")}`)}catch(e){error(e)}}async function exportData(){try{toast(`Exportado: ${await api("export_data")}`)}catch(e){error(e)}}
const formatDay=d=>new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"short"}).format(new Date(d+"T12:00:00"));const time=d=>d?.includes("T")?d.slice(11,16):"dia todo";const formatDateTime=d=>d?new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date(d)):"—";const localValue=d=>d?.slice(0,16)||"";
function toast(msg){const t=document.getElementById("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),3500)}function error(e){toast(e.message||String(e))}
